packages:
  - '.'
  - 'vue'

ignoredBuiltDependencies:
  - electron-winstaller
  - grpc-tools
  - protobufjs

onlyBuiltDependencies:
  - electron
overrides:
  squidlet-lib: link:../../../.local/share/pnpm/global/5/node_modules/squidlet-lib
