openrouterDefaultApiKey: ""
openrouterDefaultBaseUrl: https://openrouter.ai/api/v1
xdotoolBin: /usr/bin/xdotool
appLanguage: ru
userLanguage: ru
toTranslateLanguages:
  - en_US
  - ru_RU
  - es_AR
internetSearchUrl: https://duckduckgo.com/?q=
models: {}
aiModelUsage:
  voiceRecognition: ""
  fastTranslate: ""
  completion: ""
  intentionRecognition: ""
  correction: ""
  deepEdit: ""
  deepTranslate: ""
  askAI: ""
aiContexts:
  fastTranslate: ""
  completion: ""
  toCalendar: ""
  assistant: ""
  correction: ""
  askAiForText: ""
  deepEdit: []
  deepTranslate: []
