/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionsMenu: typeof import('./src/components/ActionsMenu.vue')['default']
    AiChat: typeof import('./src/components/AiChat.vue')['default']
    DropdownRow: typeof import('./src/components/DropdownRow.vue')['default']
    History: typeof import('./src/components/History.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    InputHistory: typeof import('./src/components/InputHistory.vue')['default']
    InputRow: typeof import('./src/components/InputRow.vue')['default']
    ItemsField: typeof import('./src/components/ItemsField.vue')['default']
    MainInput: typeof import('./src/components/MainInput.vue')['default']
    MainInputHistory: typeof import('./src/components/MainInputHistory.vue')['default']
    Overlays: typeof import('./src/components/Overlays.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectRow: typeof import('./src/components/SelectRow.vue')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    TextArea: typeof import('./src/components/TextArea.vue')['default']
    TextEditToolbar: typeof import('./src/components/TextEditToolbar.vue')['default']
    TransformAndInsertMenu: typeof import('./src/components/TransformAndInsertMenu.vue')['default']
    WriteMode: typeof import('./src/components/WriteMode.vue')['default']
  }
}
