/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionsMenu: typeof import('./src/components/ActionsMenu.vue')['default']
    AiChat: typeof import('./src/components/AiChat.vue')['default']
    MainInput: typeof import('./src/components/MainInput.vue')['default']
    Overlays: typeof import('./src/components/Overlays.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextEditToolbar: typeof import('./src/components/TextEditToolbar.vue')['default']
    TransformAndInsertMenu: typeof import('./src/components/TransformAndInsertMenu.vue')['default']
  }
}
